config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :shops, only: %i[new create show destroy index] do
    collection do
      get :search
    end
  end
  resources :users, only: %i[show index] do
    member do
      get :profile
      get :exchangeposts
      get :comments
    end
  end
  resources :shopposts, only: %i[create destroy]
  resources :exchangeposts, only: %i[new create index destroy show] do
    collection do
      get :search
    end
  end
  resources :comments, only: %i[create destroy]
  resources :messages, only: :destroy
  resources :conversations, only: %i[index create show] do
    resources :messages, only: %i[create]
  end
end

app/views/shared/_conversations.html.erb
<div class="list-group">
  <% users.each do |user| %>
    <%= link_to conversation_path(conversation_with(user)), class: "list-group-item list-group-item-action #{user == recipient ? ' bg-light' : ''}" do %>
      <%= image_tag user.display_image, class: "rounded-circle", width: "40" %>
      <%= user.name %>
    <% end %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" id="error_explanation" data-turbo-cache="false">
    <div class="d-flex align-items-center">
      <i class="fa-solid fa-triangle-exclamation me-2"></i>
      <h2 class="alert-heading mb-0">
        <%= I18n.t("errors.messages.not_saved",
                  count: resource.errors.count,
                  resource: resource.class.model_name.human.downcase)
        %>
      </h2>
    </div>
    <hr>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_exchangeposts.html.erb
<% exchangeposts.each_with_index do |exchangepost, i| %>
  <div class="list-group-item py-3 exchangepost-list" id="exchangepost-<%= exchangepost.id %>">
    <div class="row">
      <div class="col-md-8 d-flex">
        <div class="me-3">
          <%= image_tag exchangepost.user.display_image, alt: "User image", class: "rounded-circle flex-shrink-0", width: 50, height:50  %>
        </div>
        <div class="exchangepost w-100">
          <div class="mb-2">
            <%= link_to "投稿者：#{exchangepost.user.name}", exchangepost.user, class: "fs-6 text-wrap" %>
          </div>
          <div>
            <span class="badge bg-primary rounded-pill exchangepost-item">譲りたい</span><br>
            <span class="fs-5 text-wrap"><%= exchangepost.give_item_name %></span>
          </div>
          <small class="text-secondary"><%= exchangepost.give_item_description %></small>
          <div class="mt-2">
            <span class="badge bg-primary rounded-pill exchangepost-item">欲しい</span><br>
            <span class="fs-5 text-wrap"><%= exchangepost.want_item_name %></span>
          </div>
          <small class="text-secondary"><%= exchangepost.want_item_description %></small><br>
          <span class="badge bg-primary rounded-pill exchangepost-item mt-3">希望する交換場所</span><br>
          <span><%= exchangepost.place %></span>
          <div class="text-end mt-2 mb-3">
            <%= link_to exchangepost do %>
              <i class="fa-solid fa-angle-right me-1"></i>投稿の詳細を見る
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4 d-flex flex-column justify-content-around">
        <% if exchangepost.images.attached? %>
          <div id="carouselControls<%= i %>" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% exchangepost.images.each_with_index do |image, i| %>
                <div class="ratio ratio-1x1 carousel-item <%= "active" if i.zero? %>">
                  <%= image_tag image, alt: "exchangepost image", class: "exchangepost-img rounded w-100 d-block" %>
                </div>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselControls<%= i %>" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselControls<%= i %>" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        <% else %>
          <%= image_tag "no_image.jpg", alt: "exchangepost image", class: "exchangepost-no-img rounded w-100 d-block" %>
        <% end %>
        <div class="text-end">
          <small>更新日：<%= l exchangepost.updated_at, format: :short %></small><br>
          <small>投稿日：<%= l exchangepost.created_at, format: :short %></small><br>
          <% if current_user&.== exchangepost.user %>
            <div class="exchangepost-delete-link">
              <%= link_to exchangepost, method: :delete, class: "text-danger", data: { turbo_method: :delete, turbo_confirm: "削除してもよろしいですか？" } do %>
                <i class="fas fa-trash-alt me-1"></i>投稿を削除
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, message| %>
  <div class="d-flex justify-content-center">
    <p class="alert <%= bootstrap_class_for(key) %> flash-message px-4 py-2 mb-0 mt-4">
      <%= message %>
    </p>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('shared.links.log_in'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('shared.links.sign_up'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_messages.html.erb
<div class="card message-wrapper">
  <div class="card-header">
    <%= image_tag recipient.display_image, class: "rounded-circle", width: "40" %>
    <%= link_to recipient.name, user_path(recipient) %>
  </div>
  <div class="card-body">
    <% messages.each do |message| %>
      <div class="row mb-3">
        <% if message.user == current_user %>
          <div class="col-2 col-lg-1 px-2">
            <%= image_tag message.user.display_image, class: "rounded-circle w-100" %>
          </div>
          <div class="col-10 col-lg-11">
            <span>
              <%= link_to message.user.name, user_path(message.user), class: "message-user-link" %>
            </span>
            <p class="bg-light px-4 py-2 mb-1"><%= safe_join(message.body.split("\n"),tag(:br)) %></p>
            <div class="exchangepost-time text-end">
              <%= l message.created_at, format: :long %>
              <%= link_to message, method: :delete, class: "text-danger", data: { turbo_method: :delete, turbo_confirm: "削除してもよろしいですか？" } do %>
                <i class="fas fa-trash-alt me-1"></i>削除
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="col-10 col-lg-11">
            <div class="text-end">
              <span>
                <%= link_to recipient.name, user_path(recipient), class: "message-user-link" %>
              </span>
            </div>
            <p class="bg-light px-4 py-2 mb-1"><%= message.body %></p>
            <div class="exchangepost-time"><%= l message.created_at, format: :long %></div>
          </div>
          <div class="col-2 col-lg-1 px-2">
            <%= image_tag recipient.display_image, class: "rounded-circle w-100" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="card-footer">
    <%= form_with model: [conversation, message] do |f| %>
      <%= render "shared/error_messages", resource: message %>
      <div class="input-group">
        <%= f.text_area :body, class: 'form-control auto-expand', placeholder: 'メッセージを入力', rows: '1' %>
        <div class="input-group-append ms-1">
          <%= f.submit '送信', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div class="row col-md-10 offset-md-1 col-lg-8 offset-lg-2 user-info mb-4">
  <div class="col-md-8 col-lg-9">
    <div class="row">
      <div class="col-md-3 d-flex justify-content-center align-items-center">
        <%= image_tag user.display_image, alt: "User image", class: "rounded-circle", width: 100, height: 100 %>
      </div>
      <div class="col-md-9 d-flex flex-column justify-content-center">
        <h1 class="fs-2 m-0 text-start"><%= user.name %></h1>
        <div class="user-age-gender mt-2">
          <span>年齢: <%= user.age.present? ? user.age : '未登録' %>　|　</span>
          <span>性別: <%= user.gender.present? ? user.human_attribute_enum(:gender) : '未登録' %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-lg-3 user-btn d-flex flex-column justify-content-center align-items-stretch">
    <% if user == current_user %>
      <%= link_to 'プロフィールを編集', edit_user_registration_path, class: 'btn btn-outline-primary btn-sm my-1' %>
      <%= link_to "プロフィール詳細", profile_user_path, class: 'btn btn-outline-primary btn-sm my-1' %>
      <%= link_to "アカウント削除", users_path, method: :delete, data: { turbo_method: :delete }, class: 'btn btn-danger btn-sm my-1' %>
    <% elsif current_user %>
      <%= form_with model: conversation do |f| %>
        <%= f.hidden_field :sender_id, value: current_user.id %>
        <%= f.hidden_field :recipient_id, value: user.id %>
        <%= f.submit "DMを送る", class: "btn btn-outline-primary btn-sm w-100" %>
      <% end %>
    <% end %>
  </div>
</div>