config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :shops, only: %i[new create show destroy index] do
    collection do
      get :search
    end
  end
  resources :users, only: %i[show index] do
    member do
      get :profile
      get :exchangeposts
      get :comments
    end
  end
  resources :shopposts, only: %i[create destroy]
  resources :exchangeposts, only: %i[new create index destroy show] do
    collection do
      get :search
    end
  end
  resources :comments, only: %i[create destroy]
  resources :messages, only: :destroy
  resources :conversations, only: %i[index create show] do
    resources :messages, only: %i[create]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer border-top">
  <div class="container pt-2">
    <small>
      © <%= link_to "Look For 1", root_path %>
      by nakaty2023
    </small><br>
    <small>
      当サイト上で使用しているグッズ画像等の引用元：
      <%= link_to "一番くじ倶楽部", 'https://1kuji.com/', target: :_blank %>
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom fixed-top bg-white">
  <div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary py-2">
      <div class="container-fluid">
        <%= link_to "Look for 1", root_path, class: "fs-4 fw-bold nav-link" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item me-2">
              <%= link_to "店舗検索", root_path(anchor: 'shop_search'), class: "nav-link" %>
            </li>
            <li class="nav-item me-2">
              <%= link_to "グッズ交換投稿一覧", exchangeposts_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item me-2">
                <%= link_to current_user.name, user_path(current_user), class: "nav-link" %>
              </li>
              <div class="dropdown">
                <%= link_to "#", class: "d-block link-dark text-decoration-none dropdown-toggle", id: "dropdownUser", data: { "bs_toggle": "dropdown" }, aria: { expanded: "false" } do %>
                  <%= image_tag current_user.display_image, alt: "User image", class: "rounded-circle", width: 40, height: 40 %>
                <% end %>
                <ul class="dropdown-menu text-small dropdown-menu-end" id="dropdownMenu" aria-labelledby="dropdownUser">
                  <li>
                    <%= link_to "プロフィール", profile_user_path(current_user), class: "dropdown-item" %>
                  </li>
                  <li>
                    <%= link_to "新規投稿（グッズ交換）", new_exchangepost_path, class: "dropdown-item" %>
                  </li>
                  <li>
                    <%= link_to "投稿一覧（店舗）", current_user, class: "dropdown-item" %>
                  </li>
                  <li>
                    <%= link_to "投稿一覧（グッズ交換）", exchangeposts_user_path(current_user), class: "dropdown-item" %>
                  </li>
                  <li>
                    <%= link_to "コメント一覧（グッズ交換)", comments_user_path(current_user), class: "dropdown-item" %>
                  </li>
                  <li>
                    <%= link_to "DM", conversations_path, class: "dropdown-item" %>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "dropdown-item text-primary" %>
                  </li>
                </ul>
              </div>
            <% else %>
              <li class="nav-item me-2">
                <%= link_to "アカウント登録", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item me-2">
                <%= link_to "ログイン",  new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ゲストログイン', users_guest_sign_in_path, data: { "turbo-method": :post }, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script> window.process = {env: {}}  </script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render "shared/flash_message" %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>